import sys
sys.stdout.reconfigure(encoding='utf-8')

# agent3_generator.py
# Agent 3 — Report Generator
# Reads Agent 2 extraction JSON -> generates a formatted PDF report
# using ReportLab. No LLM needed here — pure structured output.

import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER

# ── 1. LOAD AGENT 2 OUTPUT ───────────────────────────────────
print("\n[Agent 3] Loading Agent 2 extraction results...")

with open("agent2_extractions.json", "r") as f:
    agent2_data = json.load(f)

extracted = agent2_data["extracted_fields"]
source_file = agent2_data["source_file"]
fields_extracted = agent2_data["fields_extracted"]

print(f"[Agent 3] Source document: {source_file}")
print(f"[Agent 3] Fields received: {fields_extracted}")

# ── 2. SETUP OUTPUT FILE ─────────────────────────────────────
output_pdf = "agent3_contract_report.pdf"
doc = SimpleDocTemplate(
    output_pdf,
    pagesize=A4,
    rightMargin=20*mm,
    leftMargin=20*mm,
    topMargin=20*mm,
    bottomMargin=20*mm
)

# ── 3. DEFINE STYLES ─────────────────────────────────────────
styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    fontSize=20,
    textColor=colors.HexColor("#1a1a2e"),
    spaceAfter=4,
    alignment=TA_CENTER
)

subtitle_style = ParagraphStyle(
    "SubtitleStyle",
    parent=styles["Normal"],
    fontSize=10,
    textColor=colors.HexColor("#555555"),
    spaceAfter=2,
    alignment=TA_CENTER
)

section_header_style = ParagraphStyle(
    "SectionHeader",
    parent=styles["Normal"],
    fontSize=12,
    fontName="Helvetica-Bold",
    textColor=colors.HexColor("#1a1a2e"),
    spaceBefore=12,
    spaceAfter=6
)

field_label_style = ParagraphStyle(
    "FieldLabel",
    parent=styles["Normal"],
    fontSize=9,
    fontName="Helvetica-Bold",
    textColor=colors.HexColor("#444444"),
    spaceAfter=2
)

field_value_style = ParagraphStyle(
    "FieldValue",
    parent=styles["Normal"],
    fontSize=10,
    textColor=colors.HexColor("#222222"),
    spaceAfter=8,
    leading=14
)

not_found_style = ParagraphStyle(
    "NotFound",
    parent=styles["Normal"],
    fontSize=10,
    textColor=colors.HexColor("#aaaaaa"),
    spaceAfter=8,
    fontName="Helvetica-Oblique"
)

footer_style = ParagraphStyle(
    "Footer",
    parent=styles["Normal"],
    fontSize=8,
    textColor=colors.HexColor("#999999"),
    alignment=TA_CENTER
)

# ── 4. FIELD DISPLAY NAMES ───────────────────────────────────
# Maps JSON keys -> human-readable report labels
field_labels = {
    "parties_involved":   "Parties Involved",
    "contract_date":      "Contract Date",
    "contract_duration":  "Contract Duration",
    "payment_terms":      "Payment Terms",
    "deliverables":       "Deliverables / Services",
    "termination_clause": "Termination Clause",
    "governing_law":      "Governing Law / Jurisdiction",
    "confidentiality":    "Confidentiality Clause"
}

# ── 5. BUILD PDF CONTENT ─────────────────────────────────────
print("[Agent 3] Building PDF report...")

story = []  # ReportLab builds PDF from a list of flowable elements

# — Header block —
story.append(Spacer(1, 6*mm))
story.append(Paragraph("Contract Intelligence Report", title_style))
story.append(Paragraph("Generated by Multi-Agent Document Intelligence Pipeline", subtitle_style))
story.append(Paragraph(f"Source: {source_file}", subtitle_style))
story.append(Paragraph(
    f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}",
    subtitle_style
))
story.append(Spacer(1, 4*mm))
story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a1a2e")))
story.append(Spacer(1, 6*mm))

# — Summary table —
story.append(Paragraph("Extraction Summary", section_header_style))

found_count = sum(1 for v in extracted.values() if v != "Not found")
not_found_count = fields_extracted - found_count

summary_data = [
    ["Total Fields Queried", "Fields Extracted", "Fields Not Found"],
    [str(fields_extracted), str(found_count), str(not_found_count)]
]

summary_table = Table(summary_data, colWidths=[56*mm, 56*mm, 56*mm])
summary_table.setStyle(TableStyle([
    ("BACKGROUND",   (0, 0), (-1, 0),  colors.HexColor("#1a1a2e")),
    ("TEXTCOLOR",    (0, 0), (-1, 0),  colors.white),
    ("FONTNAME",     (0, 0), (-1, 0),  "Helvetica-Bold"),
    ("FONTSIZE",     (0, 0), (-1, 0),  10),
    ("ALIGN",        (0, 0), (-1, -1), "CENTER"),
    ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
    ("FONTSIZE",     (0, 1), (-1, -1), 13),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f5f5f5")]),
    ("BOX",          (0, 0), (-1, -1), 1, colors.HexColor("#cccccc")),
    ("INNERGRID",    (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
    ("TOPPADDING",   (0, 0), (-1, -1), 8),
    ("BOTTOMPADDING",(0, 0), (-1, -1), 8),
]))

story.append(summary_table)
story.append(Spacer(1, 8*mm))
story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))

# — Extracted fields section —
story.append(Paragraph("Extracted Contract Fields", section_header_style))
story.append(Spacer(1, 2*mm))

for key, label in field_labels.items():
    value = extracted.get(key, "Not found")

    story.append(Paragraph(label, field_label_style))

    if value == "Not found":
        story.append(Paragraph("— Not found in document", not_found_style))
    else:
        story.append(Paragraph(value, field_value_style))

    # Thin divider between fields
    story.append(HRFlowable(width="100%", thickness=0.3, color=colors.HexColor("#eeeeee")))
    story.append(Spacer(1, 2*mm))

# — Footer —
story.append(Spacer(1, 8*mm))
story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
story.append(Spacer(1, 3*mm))
story.append(Paragraph(
    "Generated by ZenithQuest Multi-Agent Document Intelligence Pipeline · "
    "Agent 3: Report Generator · For internal use only",
    footer_style
))

# ── 6. BUILD & SAVE PDF ──────────────────────────────────────
doc.build(story)

print(f"[Agent 3] PDF report generated -> {output_pdf}")
print(f"[Agent 3] Fields rendered: {found_count} extracted, {not_found_count} not found")
print("\n[Agent 3] Complete. Hand-off to Agent 4 ready.")
